version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repository
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            sudo apt install python3-stdeb python3-pytest fakeroot
      - run:
          name: Test
          environment:
            GXENV_TEST: yes
          command: |
            python3 setup.py test
      - run:
          name: Debian package
          environment:
            GXENV_TEST: yes
          command: |
            make deb

